repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=25000"]
      - id: check-toml
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=80
          - --include='\.pyi?$'
          - --exclude="""\.git |\.venv|"""
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black
          - --force-single-line-imports
          - --line-length=80
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--max-line-length=80"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E266,E501,W503,F403,E402,H306,H404,H405,H301"
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==22.6.0]
        args: # arguments to configure black
          - --line-length=80
      - id: nbqa-isort
        additional_dependencies: [isort==5.10.1]
        args:
          - --profile=black
          - --force-single-line-imports
